baseURL = "https://suraj-bhadauria.github.io/"
languageCode = "en-us"
title = "Suraj Bhadauria"
theme = "PaperMod"

[params]
  ShowReadingTime = true
  ShowShareButtons = true
  ShowPostNavLinks = true
  
  ShowSummary = false
  hideSummary = true
  customCSS = ["css/extended/custom.css"]

mainSections = ["posts"]
